- name: installing utilitis
  hosts: all
  become: yes 
  vars:
    utils:
      - git 
      - tree 
      - vim
  tasks: 
    - name: install 
      ansible.builtin.apt:
        name: "{{utils}}"
        state: present 
      notify: ensure ssh is running
  handlers: 
    - name: ensure ssh is running
      ansible.builtin.systemd:
        name: sshd
        state: running
      